/**
 * Testcases for rfa/RfaWriter.h.
 *
 * @author Copyright (c) 2026
 */

#include "test_rfa_writer.h"

#include "rfa/RfaArchive.h"
#include "rfa/RfaStamp.h"
#include "rfa/RfaWriter.h"

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

using namespace rfa;

namespace {

/**
 * Locate the committed golden archives.
 *
 * These are generated by tools/rfa_golden_archives.py from bin/rfaPack.orig.exe and
 * committed. Calling the oracle from inside the test was tried first and abandoned: it
 * goes through cmd.exe, which rejects forward-slash paths and resolves relative paths
 * against its own working directory, so it failed for reasons that had nothing to do
 * with the writer.
 */
std::string golden_root()
{
	std::vector<std::string> candidates;

	if( const char * from_env = std::getenv( "RFA_TEST_DATA_DIR" ) ) {
		if( *from_env ) {
			candidates.push_back( std::string( from_env ) + "/golden" );
		}
	}

	candidates.push_back( "tests/data/golden" );
	candidates.push_back( "../tests/data/golden" );
	candidates.push_back( "../../tests/data/golden" );

	for( const std::string & candidate : candidates ) {
		if( std::filesystem::exists( std::filesystem::path( candidate ) ) ) {
			return candidate;
		}
	}

	return std::string();
}

/// Reports the first differing byte, because "31 bytes vs 31 bytes" is not a diagnosis.
void report_difference( const std::string & label,
                        const std::vector<unsigned char> & got,
                        const std::vector<unsigned char> & expected )
{
	const std::size_t limit = std::min( got.size(), expected.size() );
	std::size_t first = limit;

	for( std::size_t i = 0; i < limit; ++i ) {
		if( got[i] != expected[i] ) {
			first = i;
			break;
		}
	}

	std::cout << "[rfa] " << label << ": got " << got.size() << " bytes, expected "
	          << expected.size() << ", first difference at " << first << "\n";

	const std::size_t from = first > 8 ? first - 8 : 0;

	std::cout << "        got      :";
	for( std::size_t i = from; i < std::min( first + 8, got.size() ); ++i ) {
		std::printf( " %02X", got[i] );
	}
	std::cout << "\n        expected :";
	for( std::size_t i = from; i < std::min( first + 8, expected.size() ); ++i ) {
		std::printf( " %02X", expected[i] );
	}
	std::cout << "\n";
}

/// A scratch directory that cleans itself up, derived from a testcase scratch file name.
class Scratch
{
public:
	explicit Scratch( const std::string & seed )
	: root_( seed + ".work" )
	{
		std::error_code ec;
		std::filesystem::remove_all( root_, ec );
		std::filesystem::create_directories( root_, ec );
	}

	~Scratch()
	{
		std::error_code ec;
		std::filesystem::remove_all( root_, ec );
	}

	Scratch( const Scratch & ) = delete;
	Scratch & operator=( const Scratch & ) = delete;

	const std::string & root() const { return root_; }

	std::string path( const std::string & relative ) const
	{
		return ( std::filesystem::path( root_ ) / relative ).string();
	}

	void write( const std::string & relative, const std::vector<unsigned char> & data ) const
	{
		const std::filesystem::path full = std::filesystem::path( root_ ) / relative;

		std::error_code ec;
		std::filesystem::create_directories( full.parent_path(), ec );

		std::ofstream out( full.string().c_str(), std::ios::binary );
		out.write( (const char *)data.data(), (std::streamsize)data.size() );
	}

private:
	std::string root_;
};

std::vector<unsigned char> bytes( const std::string & text )
{
	return std::vector<unsigned char>( text.begin(), text.end() );
}

/// Deterministic pseudo-random data, so tests do not depend on <random> behaviour.
std::vector<unsigned char> pseudo_random( std::size_t size, std::uint32_t seed )
{
	std::vector<unsigned char> data;
	data.reserve( size );

	std::uint32_t state = seed;
	for( std::size_t i = 0; i < size; ++i ) {
		state = state * 1664525u + 1013904223u;
		data.push_back( (unsigned char)( state >> 24 ) );
	}

	return data;
}

std::vector<unsigned char> read_whole_file( const std::string & path )
{
	std::vector<unsigned char> data;

	std::ifstream file( path.c_str(), std::ios::binary );
	if( !file ) {
		return data;
	}

	char buffer[8192];
	for( ;; ) {
		file.read( buffer, sizeof( buffer ) );
		const std::streamsize got = file.gcount();
		if( got <= 0 ) {
			break;
		}
		data.insert( data.end(), buffer, buffer + got );
	}

	return data;
}

/// Writes a small tree under <scratch>/<name> and returns the directory holding it.
std::string make_tree( const Scratch & scratch, const std::string & name )
{
	const std::string root = scratch.path( name );

	scratch.write( name + "/a.txt", bytes( "Game.setNumberOfTickets 1 115\r\n" ) );
	scratch.write( name + "/empty.txt", std::vector<unsigned char>() );
	scratch.write( name + "/nested/deep.txt", bytes( "deep file contents\r\n" ) );
	scratch.write( name + "/blob.bin", pseudo_random( 204800, 4242 ) );   // 6.25 chunks

	return root;
}

bool build( const std::string & root,
            const std::string & base,
            const std::string & archive,
            CompressionPolicy policy,
            unsigned threads,
            std::string * error )
{
	std::vector<SourceFile> files;

	if( !RfaWriter::collect_files( root, base, files, error ) ) {
		return false;
	}

	WriteOptions options;
	options.policy = policy;
	options.threads = threads;

	RfaWriter writer;
	return writer.write( files, archive, options, nullptr, error );
}

/**
 * Byte-compares two archives, reporting where they diverge.
 *
 * Returns true only for an exact match - that is the whole point of the oracle test.
 */
bool compare_archives( const std::string & ours, const std::string & theirs, const std::string & label )
{
	const std::vector<unsigned char> a = read_whole_file( ours );
	const std::vector<unsigned char> b = read_whole_file( theirs );

	if( a.size() != b.size() ) {
		std::cout << "[rfa] " << label << ": size differs, ours=" << a.size()
		          << " oracle=" << b.size() << "\n";
	}

	const std::size_t limit = std::min( a.size(), b.size() );
	std::size_t differences = 0;
	std::size_t first = 0;

	for( std::size_t i = 0; i < limit; ++i ) {
		if( a[i] != b[i] ) {
			if( differences == 0 ) {
				first = i;
			}
			++differences;
		}
	}

	if( differences != 0 || a.size() != b.size() ) {
		std::cout << "[rfa] " << label << ": " << differences << " differing bytes in "
		          << limit << " compared, first at offset " << first << "\n";

		std::cout << "        ours   :";
		for( std::size_t i = first > 8 ? first - 8 : 0; i < std::min( first + 16, a.size() ); ++i ) {
			std::printf( " %02X", a[i] );
		}
		std::cout << "\n        oracle :";
		for( std::size_t i = first > 8 ? first - 8 : 0; i < std::min( first + 16, b.size() ); ++i ) {
			std::printf( " %02X", b[i] );
		}
		std::cout << "\n";

		return false;
	}

	return true;
}

/**
 * Structural and payload comparison, for the case where the bytes legitimately differ.
 *
 * The two archives must agree on version, entry order, names, uncompressed sizes and the
 * opaque per-entry fields, and every entry must decompress to identical bytes. That is
 * what "interchangeable" means; it does not require identical compressed streams.
 */
bool compare_archives_semantically( const std::string & ours,
                                    const std::string & theirs,
                                    const std::string & label )
{
	RfaArchive a;
	RfaArchive b;
	std::string error;

	if( !a.open( ours, &error ) ) {
		std::cout << "[rfa] " << label << ": cannot open ours: " << error << "\n";
		return false;
	}

	if( !b.open( theirs, &error ) ) {
		std::cout << "[rfa] " << label << ": cannot open the oracle: " << error << "\n";
		return false;
	}

	if( a.version() != b.version() ) {
		std::cout << "[rfa] " << label << ": version " << a.version() << " vs " << b.version() << "\n";
		return false;
	}

	if( a.entries().size() != b.entries().size() ) {
		std::cout << "[rfa] " << label << ": " << a.entries().size() << " entries vs "
		          << b.entries().size() << "\n";
		return false;
	}

	PayloadReader reader_a( ours );
	PayloadReader reader_b( theirs );

	for( std::size_t i = 0; i < a.entries().size(); ++i ) {
		const Entry & ea = a.entries()[i];
		const Entry & eb = b.entries()[i];

		if( ea.name != eb.name ) {
			std::cout << "[rfa] " << label << ": entry " << i << " is '" << ea.name
			          << "' but the oracle has '" << eb.name << "'\n";
			return false;
		}

		if( ea.uncompressed_size != eb.uncompressed_size ) {
			std::cout << "[rfa] " << label << ": " << ea.name << " uncompressedSize "
			          << ea.uncompressed_size << " vs " << eb.uncompressed_size << "\n";
			return false;
		}

		if( ea.flags != eb.flags || ea.reserved1 != eb.reserved1 || ea.reserved2 != eb.reserved2 ) {
			std::cout << "[rfa] " << label << ": " << ea.name << " opaque fields differ\n";
			return false;
		}

		std::vector<unsigned char> pa;
		std::vector<unsigned char> pb;

		if( !reader_a.read( ea, pa, &error ) || !reader_b.read( eb, pb, &error ) ) {
			std::cout << "[rfa] " << label << ": " << ea.name << " failed to decompress: "
			          << error << "\n";
			return false;
		}

		if( pa != pb ) {
			report_difference( label + " " + ea.name, pa, pb );
			return false;
		}
	}

	return true;
}

} // namespace

// ---------------------------------------------------------------------------

TestCasePtr test_writer_collect_files_names_them_base_slash_relative()
{
	return std::make_shared<TestCaseFuncOneFile>(
		"writer_collect_files_names_them_base_slash_relative",
		[]( const std::string & scratch ) {
			Scratch work( scratch );
			const std::string root = make_tree( work, "menu" );

			std::vector<SourceFile> files;
			std::string error;

			if( !RfaWriter::collect_files( root, "menu", files, &error ) ) {
				std::cout << "[rfa] collect_files failed: " << error << "\n";
				return false;
			}

			std::vector<std::string> names;
			for( const SourceFile & file : files ) {
				names.push_back( file.name );

				// forward slashes only: rfaUnpack.exe -l cannot match backslashes
				if( file.name.find( '\\' ) != std::string::npos ) {
					return false;
				}
			}

			std::sort( names.begin(), names.end() );

			const std::vector<std::string> expected = {
				"menu/a.txt", "menu/blob.bin", "menu/empty.txt", "menu/nested/deep.txt"
			};

			return names == expected;
		},
		std::ios::out );
}

TestCasePtr test_writer_store_policy_writes_version_0_raw_entries()
{
	return std::make_shared<TestCaseFuncOneFile>(
		"writer_store_policy_writes_version_0_raw_entries",
		[]( const std::string & scratch ) {
			Scratch work( scratch );
			const std::string root = make_tree( work, "menu" );
			const std::string archive = work.path( "store.rfa" );

			std::string error;
			if( !build( root, "menu", archive, CompressionPolicy::Store, 1, &error ) ) {
				std::cout << "[rfa] write failed: " << error << "\n";
				return false;
			}

			RfaArchive written;
			if( !written.open( archive, &error ) ) {
				std::cout << "[rfa] cannot reopen store.rfa: " << error << "\n";
				return false;
			}

			// rfaPack.exe writes version 0 and raw entries when -Compress is absent
			if( written.version() != VERSION_0 || !written.problems().empty() ) {
				return false;
			}

			for( const Entry & entry : written.entries() ) {
				if( entry.variant != PayloadVariant::Raw ) {
					return false;
				}
				if( entry.stored_size != entry.uncompressed_size ) {
					return false;
				}
			}

			// data starts where every observed archive puts it
			return written.entries().size() == 4
			    && written.entries()[0].data_offset == DEFAULT_FIRST_DATA_OFFSET;
		},
		std::ios::out );
}

TestCasePtr test_writer_compress_policy_writes_version_1_chunked_entries()
{
	return std::make_shared<TestCaseFuncOneFile>(
		"writer_compress_policy_writes_version_1_chunked_entries",
		[]( const std::string & scratch ) {
			Scratch work( scratch );
			const std::string root = make_tree( work, "menu" );
			const std::string archive = work.path( "compress.rfa" );

			std::string error;
			if( !build( root, "menu", archive, CompressionPolicy::Compress, 1, &error ) ) {
				std::cout << "[rfa] write failed: " << error << "\n";
				return false;
			}

			RfaArchive written;
			if( !written.open( archive, &error ) ) {
				return false;
			}

			if( written.version() != VERSION_1 || !written.problems().empty() ) {
				return false;
			}

			// every entry chunked; a version-1 archive must never hold a raw non-empty
			// entry, because rfaUnpack.exe crashes trying to decompress one
			for( const Entry & entry : written.entries() ) {
				if( entry.variant != PayloadVariant::Chunked ) {
					return false;
				}
				if( entry.uncompressed_size > 0 && entry.stored_size == entry.uncompressed_size ) {
					return false;
				}
			}

			const Entry * blob = written.find( "menu/blob.bin" );

			return blob != nullptr
			    && blob->chunk_count() == chunk_count_for( blob->uncompressed_size )
			    && blob->chunk_count() == 7;
		},
		std::ios::out );
}

TestCasePtr test_writer_round_trips_a_tree_through_our_reader()
{
	return std::make_shared<TestCaseFuncOneFile>(
		"writer_round_trips_a_tree_through_our_reader",
		[]( const std::string & scratch ) {
			Scratch work( scratch );
			const std::string root = make_tree( work, "menu" );

			for( CompressionPolicy policy : { CompressionPolicy::Store, CompressionPolicy::Compress } ) {
				const std::string archive = work.path( policy == CompressionPolicy::Store
				                                     ? "rt_store.rfa" : "rt_compress.rfa" );

				std::string error;
				if( !build( root, "menu", archive, policy, 1, &error ) ) {
					return false;
				}

				RfaArchive written;
				if( !written.open( archive, &error ) || !written.problems().empty() ) {
					return false;
				}

				PayloadReader reader( archive );

				for( const Entry & entry : written.entries() ) {
					std::vector<unsigned char> payload;
					if( !reader.read( entry, payload, &error ) ) {
						std::cout << "[rfa] " << error << "\n";
						return false;
					}

					const std::string relative = entry.name.substr( std::string( "menu/" ).size() );
					const std::vector<unsigned char> expected = read_whole_file( work.path( "menu/" + relative ) );

					if( payload != expected ) {
						report_difference( entry.name, payload, expected );
						return false;
					}
				}
			}

			return true;
		},
		std::ios::out );
}

TestCasePtr test_writer_multi_chunk_entry_round_trips()
{
	return std::make_shared<TestCaseFuncOneFile>(
		"writer_multi_chunk_entry_round_trips",
		[]( const std::string & scratch ) {
			Scratch work( scratch );

			// incompressible: every chunk is larger compressed than raw, which is the
			// case most likely to expose a chunk-boundary mistake
			const std::vector<unsigned char> big = pseudo_random( 5 * 32768 + 17, 99 );
			work.write( "menu/big.bin", big );

			const std::string root = work.path( "menu" );
			const std::string archive = work.path( "multi.rfa" );

			std::string error;
			if( !build( root, "menu", archive, CompressionPolicy::Compress, 4, &error ) ) {
				return false;
			}

			RfaArchive written;
			const bool opened = written.open( archive, &error );

			if( !opened ) {
				std::cout << "[rfa] cannot open the multi-chunk archive: " << error << "\n";
				return false;
			}

			if( !written.problems().empty() ) {
				std::cout << "[rfa] multi-chunk archive reported problems:";

				for( const std::string & problem : written.problems() ) {
					std::cout << "\n        " << problem;
				}

				std::cout << "\n";
				return false;
			}

			const Entry * entry = written.find( "menu/big.bin" );

			if( entry == nullptr ) {
				std::cout << "[rfa] menu/big.bin not found in the written archive\n";
				return false;
			}

			if( entry->chunk_count() != 6 ) {
				std::cout << "[rfa] menu/big.bin has " << entry->chunk_count()
				          << " chunks, expected 6 (unc=" << entry->uncompressed_size << ")\n";
				return false;
			}

			std::vector<unsigned char> payload;
			PayloadReader reader( archive );

			if( !reader.read( *entry, payload, &error ) ) {
				std::cout << "[rfa] " << error << "\n";
				return false;
			}

			if( payload != big ) {
				report_difference( "menu/big.bin", payload, big );
				return false;
			}

			return true;
		},
		std::ios::out );
}

TestCasePtr test_writer_empty_file_round_trips_in_both_policies()
{
	return std::make_shared<TestCaseFuncOneFile>(
		"writer_empty_file_round_trips_in_both_policies",
		[]( const std::string & scratch ) {
			Scratch work( scratch );
			work.write( "menu/empty.txt", std::vector<unsigned char>() );
			work.write( "menu/other.txt", bytes( "x" ) );

			for( CompressionPolicy policy : { CompressionPolicy::Store, CompressionPolicy::Compress } ) {
				const std::string archive = work.path( policy == CompressionPolicy::Store
				                                     ? "empty_store.rfa" : "empty_compress.rfa" );

				std::string error;
				if( !build( work.path( "menu" ), "menu", archive, policy, 1, &error ) ) {
					return false;
				}

				RfaArchive written;
				if( !written.open( archive, &error ) || !written.problems().empty() ) {
					std::cout << "[rfa] empty " << ( policy == CompressionPolicy::Store ? "store" : "compress" )
					          << " archive reported problems\n";
					for( const std::string & problem : written.problems() ) {
						std::cout << "        " << problem << "\n";
					}
					return false;
				}

				const Entry * empty = written.find( "menu/empty.txt" );
				if( empty == nullptr || empty->uncompressed_size != 0 ) {
					return false;
				}

				std::vector<unsigned char> payload;
				PayloadReader reader( archive );

				if( !reader.read( *empty, payload ) || !payload.empty() ) {
					return false;
				}
			}

			return true;
		},
		std::ios::out );
}

TestCasePtr test_writer_orders_entries_like_the_oracle()
{
	// rfaPack.exe does not sort by full path: it emits each directory's own regular files
	// (sorted) before descending into its subdirectories (sorted). Entry order reaches the
	// archive table verbatim, so matching it is what makes byte-identical output possible.
	// Verified against the real tool with two nesting levels and several siblings.
	return std::make_shared<TestCaseFuncOneFile>(
		"writer_orders_entries_like_the_oracle",
		[]( const std::string & scratch ) {
			Scratch work( scratch );

			work.write( "menu/z.txt", bytes( "z" ) );
			work.write( "menu/a.txt", bytes( "a" ) );
			work.write( "menu/d1/c.txt", bytes( "c" ) );
			work.write( "menu/d1/e/f.txt", bytes( "f" ) );
			work.write( "menu/d2/b.txt", bytes( "b" ) );

			std::vector<SourceFile> files;
			std::string error;

			if( !RfaWriter::collect_files( work.path( "menu" ), "menu", files, &error ) ) {
				return false;
			}

			std::vector<std::string> names;
			for( const SourceFile & file : files ) {
				names.push_back( file.name );
			}

			// note: NOT ASCII-ascending, which would put menu/z.txt last
			const std::vector<std::string> expected = {
				"menu/a.txt", "menu/z.txt", "menu/d1/c.txt", "menu/d1/e/f.txt", "menu/d2/b.txt"
			};

			if( names != expected ) {
				std::cout << "[rfa] entry order differs from the oracle walk order:\n";
				for( const std::string & name : names ) {
					std::cout << "        got " << name << "\n";
				}
				return false;
			}

			return true;
		},
		std::ios::out );
}

TestCasePtr test_writer_is_deterministic_across_thread_counts()
{
	// Thread scheduling must not influence the output, or archives become uncomparable.
	return std::make_shared<TestCaseFuncOneFile>(
		"writer_is_deterministic_across_thread_counts",
		[]( const std::string & scratch ) {
			Scratch work( scratch );
			work.write( "menu/a.bin", pseudo_random( 200000, 7 ) );
			work.write( "menu/b.bin", pseudo_random( 150000, 8 ) );
			work.write( "menu/c.txt", bytes( "text\r\n" ) );

			std::string error;

			if( !build( work.path( "menu" ), "menu", work.path( "t1.rfa" ),
			            CompressionPolicy::Compress, 1, &error ) ) {
				return false;
			}
			if( !build( work.path( "menu" ), "menu", work.path( "t8.rfa" ),
			            CompressionPolicy::Compress, 8, &error ) ) {
				return false;
			}

			return compare_archives( work.path( "t1.rfa" ), work.path( "t8.rfa" ), "threads 1 vs 8" );
		},
		std::ios::out );
}

TestCasePtr test_writer_missing_source_leaves_no_archive()
{
	return std::make_shared<TestCaseFuncOneFile>(
		"writer_missing_source_leaves_no_archive",
		[]( const std::string & scratch ) {
			Scratch work( scratch );
			const std::string archive = work.path( "partial.rfa" );

			std::error_code ec;
			std::filesystem::remove( archive, ec );

			std::vector<SourceFile> files;
			SourceFile file;
			file.name = "menu/missing.bin";
			file.path = "definitely/not/here.bin";
			files.push_back( file );

			WriteOptions options;
			RfaWriter writer;

			std::string error;
			const bool ok = writer.write( files, archive, options, nullptr, &error );

			// a failed pack must not leave a half-written archive that looks valid
			return !ok && !error.empty() && !std::filesystem::exists( archive );
		},
		std::ios::out );
}

TestCasePtr test_writer_matches_the_golden_store_archive_byte_for_byte()
{
	// With no compression involved, our archive must be byte-identical to rfaPack.exe's.
	// This transitively pins the 148-byte reserved region, the first data offset (156),
	// the reserved entry field, the version, the table layout and the entry ORDER - so a
	// pass here is strong evidence of a true drop-in replacement.
	return std::make_shared<TestCaseFuncOneFile>(
		"writer_matches_the_golden_store_archive_byte_for_byte",
		[]( const std::string & scratch ) {
			Scratch work( scratch );
			const std::string root = golden_root();

			if( root.empty() ) {
				std::cout << "[rfa] tests/data/golden not found; run tools/rfa_golden_archives.py\n";
				return false;
			}

			const std::string ours = work.path( "ours-store.rfa" );

			std::string error;
			if( !build( root + "/tree", "menu", ours, CompressionPolicy::Store, 1, &error ) ) {
				std::cout << "[rfa] our writer failed: " << error << "\n";
				return false;
			}

			return compare_archives( ours, root + "/oracle-store.rfa", "store" );
		},
		std::ios::out );
}

TestCasePtr test_writer_compress_archive_is_interchangeable_with_the_oracle()
{
	// Deliberately NOT a byte comparison. RFA Pack 1.7 embeds a 2003-era LZO whose
	// lzo1x_1_compress picks different (equally valid) matches than the miniLZO 2.10 we
	// vendor, so the compressed streams differ while the archives stay interchangeable:
	// same entries in the same order, same sizes, same opaque fields, and every payload
	// decompresses to identical bytes.
	return std::make_shared<TestCaseFuncOneFile>(
		"writer_compress_archive_is_interchangeable_with_the_oracle",
		[]( const std::string & scratch ) {
			Scratch work( scratch );
			const std::string root = golden_root();

			if( root.empty() ) {
				std::cout << "[rfa] tests/data/golden not found; run tools/rfa_golden_archives.py\n";
				return false;
			}

			const std::string ours = work.path( "ours-compress.rfa" );

			std::string error;
			if( !build( root + "/tree", "menu", ours, CompressionPolicy::Compress, 1, &error ) ) {
				std::cout << "[rfa] our writer failed: " << error << "\n";
				return false;
			}

			return compare_archives_semantically( ours, root + "/oracle-compress.rfa", "compress" );
		},
		std::ios::out );
}
