#!/usr/bin/env python3
"""Generate the fixed input tree and the oracle archives used by the writer byte-comparison.

The C++ writer test needs to prove that our archives are byte-for-byte identical to
rfaPack.exe's. Running rfaPack.exe from inside the test turned out to be fragile - it goes
through cmd.exe, which mangles forward-slash paths and resolves relative paths against its
own working directory - so the oracle output is generated here instead, once, and committed:

    tests/data/golden/tree/            the fixed input tree (byte-stable by construction)
    tests/data/golden/oracle-store.rfa     rfaPack.exe                <tree> menu <out>
    tests/data/golden/oracle-compress.rfa  rfaPack.exe -Compress      <tree> menu <out>
    tests/data/golden/MANIFEST.txt     provenance and hashes

The test packs the committed tree with our writer and compares against these. Because the
input bytes are the committed ones, there is no way for the two sides to drift.

Usage:
    python tools/rfa_golden_archives.py            # (re)generate
    python tools/rfa_golden_archives.py --check    # regenerate in a temp dir and compare
"""

from __future__ import annotations

import argparse
import hashlib
import os
import shutil
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PACK = REPO_ROOT / "bin" / "rfaPack.orig.exe"
GOLDEN = REPO_ROOT / "tests" / "data" / "golden"
TREE = GOLDEN / "tree"
BASE = "menu"

# The tree deliberately covers every payload shape the writer can produce:
#   a.txt      31 bytes   single chunk, compresses
#   tiny.txt    1 byte    LZO EXPANDS it (5 bytes) - the case a naive size check gets wrong
#   empty.txt   0 bytes   the empty encoding, which differs between store and compress
#   deep.txt              a nested path, to exercise forward-slash naming
#   blob.bin  200000 B    7 chunks of incompressible data
FILES: list[tuple[str, bytes]] = [
    ("menu/a.txt", b"Game.setNumberOfTickets 1 115\r\n"),
    ("menu/tiny.txt", b"x"),
    ("menu/empty.txt", b""),
    ("menu/nested/deep.txt", b"deep file contents\r\n"),
    ("menu/blob.bin", bytes(((i * 1664525 + 1013904223) >> 24) & 0xFF for i in range(200000))),
]


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest().upper()


def build_tree(root: Path) -> None:
    for relative, content in FILES:
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)


def run_pack(tree: Path, archive: Path, compress: bool) -> None:
    argv = [str(PACK), str(tree), BASE, str(archive)]
    if compress:
        argv.append("-Compress")

    proc = subprocess.run(argv, capture_output=True, text=True)
    if not archive.is_file():
        raise SystemExit(
            f"rfaPack.exe produced no archive (rc={proc.returncode})\n{proc.stdout}\n{proc.stderr}"
        )


def describe(archive: Path) -> str:
    data = archive.read_bytes()
    toc, version = struct.unpack_from("<II", data, 0)
    count, = struct.unpack_from("<I", data, toc)
    lines = [f"    version={version} entries={count} size={len(data)}"]

    off = toc + 4
    for _ in range(count):
        name_len, = struct.unpack_from("<I", data, off)
        off += 4
        name = data[off : off + name_len].decode("latin-1")
        off += name_len
        stored, uncompressed, data_offset, r1, r2, flags = struct.unpack_from("<IIIIII", data, off)
        off += 24

        # equality first: a chunked entry holding a 4-byte LZO stream for an empty file
        # has stored != unc, while a genuinely raw entry has stored == unc
        if stored == uncompressed:
            shape = "raw/empty"
        else:
            chunks, = struct.unpack_from("<I", data, data_offset)
            shape = f"chunked({chunks})"

        lines.append(
            f"    {name:22} stored={stored:7} unc={uncompressed:7} "
            f"dataOffset={data_offset:6} r1={r1} flags=0x{flags:08X} {shape}"
        )

    return "\n".join(lines)


def generate(root: Path) -> Path:
    tree = root / "tree"
    build_tree(tree)

    store = root / "oracle-store.rfa"
    compress = root / "oracle-compress.rfa"

    run_pack(tree, store, compress=False)
    run_pack(tree, compress, compress=True)

    return root


def render_manifest(root: Path) -> str:
    store = root / "oracle-store.rfa"
    compress = root / "oracle-compress.rfa"

    lines = [
        "Golden archives for the RFA writer byte-comparison.",
        "",
        "GENERATED by tools/rfa_golden_archives.py using bin/rfaPack.orig.exe (RFA Pack 1.7).",
        "The C++ test packs tests/data/golden/tree with our writer and compares byte for byte,",
        "so these MUST be regenerated whenever the inputs or the writer change.",
        "",
        "NOTE: regenerate only with a deliberate intent to change the expectation.",
        "",
        "input tree:",
    ]

    for relative, content in FILES:
        lines.append(f"  {relative:22} {len(content):8} bytes  sha256 {hashlib.sha256(content).hexdigest().upper()}")

    lines += [
        "",
        f"oracle-store.rfa     {store.stat().st_size:8} bytes  sha256 {sha256(store)}",
        f"oracle-compress.rfa  {compress.stat().st_size:8} bytes  sha256 {sha256(compress)}",
        "",
        "structure:",
        "  stores rfaPack.exe            <tree> menu <archive>",
        "  stores rfaPack.exe -Compress  <tree> menu <archive>",
        "",
        "oracle-store.rfa:",
        describe(store),
        "",
        "oracle-compress.rfa:",
        describe(compress),
        "",
    ]

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="regenerate elsewhere and compare against the committed files")
    args = parser.parse_args(argv)

    if args.check:
        tmp = Path(tempfile.mkdtemp(prefix="rfa_golden_"))
        try:
            generate(tmp)
            differences = []
            for name in ("oracle-store.rfa", "oracle-compress.rfa"):
                if sha256(tmp / name) != sha256(GOLDEN / name):
                    differences.append(name)

            if differences:
                print(f"golden archives differ: {', '.join(differences)}", file=sys.stderr)
                return 1

            print("golden archives match the oracle")
            return 0
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    generate(GOLDEN)
    (GOLDEN / "MANIFEST.txt").write_text(render_manifest(GOLDEN), encoding="utf-8", newline="\n")

    print(f"wrote {GOLDEN.relative_to(REPO_ROOT)}")
    print(f"  oracle-store.rfa     {sha256(GOLDEN / 'oracle-store.rfa')}")
    print(f"  oracle-compress.rfa  {sha256(GOLDEN / 'oracle-compress.rfa')}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
